### ISSUE TITLE
Service Names with spaces

### ISSUE THREAD

**Issue by fisihh** [maurobussini/winsc#1]
Hi

The Functions start,stop and status (i did not test install oder uninstall) have a problem with spaces in the serviceName.
I fixed it localy with: (for example)
 ```
     -           exec("sc.exe stop " + serviceName, (err, stdout) => {
     +          exec("sc.exe stop "\"" + serviceName + "\"", (err, stdout) => {
```

**Comment by maurobussini** [comment]
Hi fisihh, thanks for the suggestion. Fixed!
